### ISSUE TITLE
Implement `git` depth and git lfs features

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#107]
Either by invoking the `git` command (as `conda-build` does) or by using `libgit2`. Both have their pro's and cons.

**Comment by ruben-arts** [comment]
Discussion with @wolfv 
Pointers:
- Initially use the command line `git` of the system that it is run on. 
- Implement the caching from conda-build to speed up reruns of a build while cloning https://github.com/conda/conda-build/blob/main/conda_build/source.py#L413


Possible improvements:
- Look at how cargo deals with the dependencies
- Use `libgit2` crate instead of system git.

**Comment by ruben-arts** [comment]
Initial implementation is made, there are some TODO's left:
- Implement the `git_depth` for the cloning, libgit2 has no support for the ATM.
- Implement `git-lfs` it now just does normal clones.

**Comment by wolfv** [comment]
We have an implementation using `libgit2` but that has given us a bit of a headache when compiling `rattler-build`. We'd be OK with removing the `libgit2` implementation and instead to rely on the host system to provide the `git` executable and using a `Command` to invoke the git from the host system.

This has some advantages (`git-lfs` support, same config as on the host system, etc...), and it's also how `conda-build` does it. 

https://github.com/conda/conda-build/blob/e2916a2a5c590382323de97da6ac2fe6c516ff89/conda_build/source.py#L421
