### ISSUE TITLE
use `--host-platform` instead of `--target-platform`

### ISSUE THREAD

**Issue by beckermr** [prefix-dev/rattler-build#1075]
@isuruf would like to see us use `--host-platform` instead of `--target-platform` when calling `rattler-build`. 

We should add an alias for now.

xref: https://github.com/conda-forge/conda-smithy/pull/2070#discussion_r1781752261

**Comment by wolfv** [comment]
This goes beyond just the CLI argument: `target_platform` is used throughout the build process and is even part of the hash. It's part of _every_ variant (e.g. you can always do `if: target_platform == build_platform` etc.

I think renaming it is relatively _breaking_ at this point.

We could still alias it, but the question would be if we want to phase out target_platform over the long run. 

Personally it doesn't bother me so much. I am a little sad that it only comes up now (after rattler-build has been around for quite some time) - would have been cool to discuss this earlier (or as part of a CEP).

**Comment by isuruf** [comment]
> as part of a CEP

We did discuss the in the case of `requirements` where we went with `build` and `host`, but not exactly `_platform`.

I'm not saying we remove `target_platform`. In almost all cases `host_platform == target_platform` and differs only in the case of compilers.
We should use `host_platform` to mean the platform of `host` and `build_platform` to mean the platform of `build` which makes it clear.
`target_platform` is the platform where the code generated by the compiler can run on instead of the platform where the compiler is run.
