### ISSUE TITLE
Hash added to package name with rattler-build but not mambabuild

### ISSUE THREAD

**Issue by neda-dtu** [prefix-dev/rattler-build#172]
I have created a [small project](https://github.com/neda-dtu/rattler_build_test) for testing rattler-build, using the approach we use on many of our projects. 

In this project, I run `conda mambabuild` and `rattler-build build` and get different results for the names of the resulting files. Mambabuild returns a file without a hash, e.g. `rattler_build_test-0.0.2-0.tar.bz2`, while rattler-build returns a file with the has included e.g. `rattler_build_test-0.0.1-pyh4616a5c_0.tar.bz2`

**Comment by wolfv** [comment]
First of all, thanks for the great reproducer. Very helpful! 

I have been thinking about this just now.

conda-build does indeed contain a special handling for variants that only contain the "target_platform" key: https://github.com/conda/conda-build/blob/aefdab62c40476c0f213a9f9eea80cda5259b08e/conda_build/metadata.py#L1602

However, I don't think we want to follow the logic of `conda-build` here, and instead by default always include the hash in the package (file-)name. This is important so that packages do not overlap in the cache (otherwise you might produce two packages for two platforms that write to the same file in your package cache).

If you want to configure your output to exactly match the `conda-build` output, then you can set the build string manually in the `build` section:


```
build:
  string: "0"
  # or string: "${{ build_number }}" when you have build number defined in the context.
```

**Comment by neda-dtu** [comment]
Thanks for looking at this. I think you are right that keeping the hash is a better default. I noticed the lack of hash often came with noarch python projects. At the time I was looking at this, it seemed that there was not a lot of data being used in the hash creation, so a hash collision still might have occurred. Perhaps this has been changed now.

I didn't notice the string argument for the build "number", which I think is a good alternative if someone needs a specific value. 

My initial concern was about how package resolution might be affected, but as I have read more in your blog post about how package resolution takes place, I can see the hash doesn't really matter. For others like me who might find this confusing, I wonder if adding a note about in the documentation, perhaps in the [major differences with conda-build](https://prefix-dev.github.io/rattler-build/recipe_file.html#major-differences-with-conda-build) section would make sense.

**Comment by wolfv** [comment]
Yes, that could be great! Do you want to send a PR?

**Comment by neda-dtu** [comment]
Sure.

**Comment by swarnimarun** [comment]
There are now docs for this, so unsure if this requires any further work, https://prefix-dev.github.io/rattler-build/recipe_file/#build-number-and-string

If the docs look insufficient feel free to suggest improvements and reopen the issue. :3
